language: erlang
install: dialyzer --build_plt --apps erts kernel stdlib --output_plt .plt
script: rebar compile && rebar skip_deps=true eunit && dialyzer --plt .plt ./ebin
otp_release:
  - R15B02
  - 19.2

